# Site settings
title: CH Engineering
email: devchanghwan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Experience and Thinking about Software Development

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.k10n.me"
github_username: devchanghwan
linkedin_username: devchanghwan
# Build settings
copyright: Copyright 2016-2023. Ju-won Lee. All rights reserved.

theme: minima
plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
- jekyll-toc
- jekyll-sitemap
- jekyll-last-modified-at

minima:
  skin: dark
  show_excerpts: true
  nav_pages:
  - about.md
  - archive.md
  - tags.md
