# Site settings
title: Chnaghwan
email: devchanghwan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  소프트웨어 개발에 대한 경험과 지식을 이야기합니다.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.k10n.me"
github_username: ChanghwanK
linkedin_username: changhwan-kim-767139219
# Build settings
copyright: Copyright 2016-2023. Ju-won Lee. All rights reserved.

theme: minima
plugins:
- jekyll-seo-tag
- jekyll-feed
- jekyll-archives
- jekyll-toc
- jekyll-sitemap
- jekyll-last-modified-at
- jekyll-mermaid

minima:
  skin: dark
  show_excerpts: true
  nav_pages:
  - about.md
  - archive.md
  - tags.md

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.js
